name: publish-to-pypi

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build release wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a wheel and source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*any*.whl
            dist/*.tar.gz
  publish-test:
    name: Publish to PyPI
    needs: build-release
    runs-on: ubuntu-latest
    environment: PyPI
    steps:
      - name: Retrieve built archive
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
