name: try-build

on:
  push:
    paths:
      - '*.py'
      - 'pyproject.toml'

jobs:
  build-debug:
    name: Build wheel for debugging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a test wheel
        run: >-
          python -m
          build
          --wheel
          --outdir dist/
      - name: Upload artifact for testing
        uses: actions/upload-artifact@v2
        with:
          name: test-out
          path: dist
